# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160728_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 8, 50, 36, 770912, tzinfo=utc)),
        ),
    ]
